### PR TITLE
Fix Interactive.remove() method for javascript

### PR DESCRIPTION
**Pull request by nbarium**
I haven't tested the java version of the method. Anyway, the javascript version was broken.

Also, I'm still trying to understand the need for "return ae" in the method, as it always returns null. Should it return the input object when it's a single one?

### CODE REVIEW

**Comment by fjenett** [comment]
Returning ae: i think that was a copy-paste error introduced when adding .remove() .. thinking about it yes, it should return the removed elements (array of ActiveElements with one or more items or [] instead of null).

**Comment by nbarium** [comment]
I'll take care of that return ae and I think I will also bring some uniformity to add and remove, since their arguments now are from different types and, for the sake of coherence, they should be the same.

**Comment by fjenett** [comment]
Super. Tx!

**Comment by nbarium** [comment]
Plz don't thank me :) I should, instead, thank you for this great lib. Concerning the correction, shouldn't the .add() also return the same kind of array as .remove()? In the current code it returns null when the input is an array.

**Comment by fjenett** [comment]
Jup. That makes sense. Tx!

**Comment by nbarium** [comment]
I have been busy but I will take care of that next week.

**Comment by fjenett** [comment]
Cool. No problem.

**Pull request merged**
